version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
        - 3306:3306

  redis:
    hostname: redis
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - $PWD/.data/redis:/var/lib/redis
      # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  mongo:
    hostname: mongo
    image: mongo
    volumes:
      - $PWD/.data/mongo:/data/db
    ports:
      - '27017-27019:27017-27019'
